### PR TITLE
responsive version

### PR DESCRIPTION
**Pull request by agallou**
some screenshots:

screen shot 2016-12-11 at 22 54 33

screen shot 2016-12-11 at 22 54 41

### CODE REVIEW

**Comment by Hywan** [comment]
Double menu? Is it a joke oO ?

**Comment by agallou** [comment]
it's not a joke. 

before this PR, the extensions looked like that:
screen shot 2016-12-12 at 12 52 24

It was not usable on mobile (kind of like the the documentation for the moment) : the content were not displayed.

What's your suggestion / PR to improve that ?

**Comment by Hywan** [comment]
I don't know yet, but this is absolutely terrible :-/. Can we revert it?

**Comment by agallou** [comment]
Why revert it ? Have you seen the previous version ? At least we can now see the content on mobile. 
I'll try to propose something else during this week. In the meantime, feel free to propose an idea to avoid the menu. 
When we will found it, I'll transpose it to the documentation website.

**Pull request merged**
